### ISSUE TITLE
Weapons ignore durability and cooldown

### ISSUE THREAD

**Issue by Leeo97one** [TheOnlySilverClaw/Reforged#159]
The durability of most weapons does not loose durability when hitting some mobs or players.
Furthermore, all the weapons totally ignore the cooldown system introduced in the Combat Update of Minecraft.
All of this are very unbalanced, especially with the katana.

**Comment by ThexXTURBOXx** [comment]
Which version of Minecraft are you using? The cool down system gets integrated later on... I just want to release the mod for many other versions in a similar way to 1.8.
The next update (0.7.2) will bring the Offhand-support and so on.

**Comment by Leeo97one** [comment]
I'm using the latest version of the mod (0.7.1-hotfix1) with Minecraft 1.11.2.
And what about the durability loosing?

**Comment by ThexXTURBOXx** [comment]
Ok, I will take a look at that, thanks for reporting :)

**Comment by ThexXTURBOXx** [comment]
Fixed in next release :)

**Comment by Leeo97one** [comment]
Thanks, keep up the good work!

**Comment by ThexXTURBOXx** [comment]
No, problem. I thank you for reporting :)
