### ISSUE TITLE
Battleaxe does not do more damage??

### ISSUE THREAD

**Issue by ImadethisjustforNVIDIAFleX** [TheOnlySilverClaw/Reforged#161]
I was using the battleaxe and noticed it took at least 20 hits just to kill a villager, even though in the wiki it says it deals more damage. My config is not changed so idk if this is a bug or an unbalanced feature

**Comment by ThexXTURBOXx** [comment]
Are you sure, you upgraded to version 0.7.2? I saw that bug myself, but it should be fixed in the newest version (released it yesterday)

**Comment by ImadethisjustforNVIDIAFleX** [comment]
It's working now!

**Comment by ThexXTURBOXx** [comment]
Yay! ^^
