### ISSUE TITLE
Javelin Duplicates When Thrown

### ISSUE THREAD

**Issue by Darkosto** [TheOnlySilverClaw/Reforged#162]
Hello!

I was checking out this and found some really cool stuff, thank you for all your hard work!

I seem to have come across a duplication bug when throwing the Javelin. When it lands on the ground it splits into 2-4 more javelins.

Short Video: https://i.artdude.uk/darkosto/A8lTTwrN.mp4

MC: 1.11.2
Forge: 2310
Reforged: 0.7.2

Thanks for looking into this!
Darkosto

**Comment by ThexXTURBOXx** [comment]
Hey, thank you for reporting :) 
This bug is rather weird. I will definitely try to fix it :D

**Comment by ThexXTURBOXx** [comment]
I tried to reproduce this bug, but I oddly can't :/
I saw, that you have other mods installed, too. Could you try to reproduce this without them?

**Comment by TheOnlySilverClaw** [comment]
Hmm... did this happen in single or multiplayer? I would guess some logic in Javelin's onImpact-Method does not cover all combinations of gamemode and server-client-combination correctly.

**Comment by ThexXTURBOXx** [comment]
Silvercatcher is back and he's right :D
I tested it on a server and yes, it duplicates then
