### ISSUE TITLE
Refresh the translations maybe?

### ISSUE THREAD

**Issue by Pivoslave** [TheOnlySilverClaw/Reforged#163]
Oh it was so long since my activity on GitHub. Is there any new lines for me to translate?

**Comment by ThexXTURBOXx** [comment]
Hi Den! Yes, there are some. You only need to compare the en_gb.lang with the uk_ua.lang.
I think, that the subtitles, maces, Dirks and pikes are missing, but I'm not sure.

**Comment by Pivoslave** [comment]
Aha, pulled the fixing request

**Comment by ThexXTURBOXx** [comment]
I added the missing strings in english ;) Thanks for the help btw ^^
