### ISSUE TITLE
[BUGs] 1.10.2

### ISSUE THREAD

**Issue by Lockheart34** [TheOnlySilverClaw/Reforged#166]
I found many bugs in the 1.10.2 version uploaded the 7th of june:

- [x] Throwing a boomerang and quit the game instance make the game crash when i load my world
- [x] Blunderbuss doesn't hurt mobs
- [x] Crossbow has infinte arrows  ( negative number allowed ?)
- [x] Javelin animation throwns 2 javelins

**Comment by ThexXTURBOXx** [comment]
Fixed in next update
