### ISSUE TITLE
Use forge:ore_shaped and forge:ore_shapeless for weaponry recipes

### ISSUE THREAD

**Issue by Sunconure11** [TheOnlySilverClaw/Reforged#175]
This would allow for better cross-compat, and even support vanilla a bit more.

If you want to see some examples of how to do it, look at my own mod.

https://github.com/Um-Mitternacht/Witchworks/blob/1.12.1/src/main/resources/assets/witchworks/recipes/silver_ingot.json

https://github.com/Um-Mitternacht/Witchworks/blob/1.12.1/src/main/resources/assets/witchworks/recipes/athame.json

**Comment by ThexXTURBOXx** [comment]
Yes, this is indeed a clever change. I will do that in a few days hopefully
