### ISSUE TITLE
Crafting mishap

### ISSUE THREAD

**Issue by daviddoodles** [TheOnlySilverClaw/Reforged#177]
there is some problem relating about the fact that some crafting recipes dont match the one like the wooden weapons

they use LOGS instead of planks

**Comment by ThexXTURBOXx** [comment]
Do you mean the Mace for instance? If yes, this is intended behavior

**Comment by ThexXTURBOXx** [comment]
I am still unsure about this issue, sadly. Closing this until further context is provided
