### ISSUE TITLE
Random tick loop server crashes, 

### ISSUE THREAD

**Issue by kiwifrogg** [TheOnlySilverClaw/Reforged#178]
This might be a tricky one to track down however, something produces an Exception in server tick loop at random times. I know none of the players on at the time were your weapons, so it might be something a mob was carrying. This has happened 3 or 4 times in the past few days after an update to forge. 

[crash-2017-12-04_13.29.34-server.txt](https://github.com/ThexXTURBOXx/Reforged/files/1525725/crash-2017-12-04_13.29.34-server.txt)

**Comment by kiwifrogg** [comment]
Looks like this was a forge issue, i'll confirm in a day or so.

**Comment by ThexXTURBOXx** [comment]
It's half a Forge and half a Reforged issue... I already tried very much to solve this, but maybe I can figure out one day, how it works right :)

**Comment by ThexXTURBOXx** [comment]
Could be fixed in the latest version. I am unsure, however.
