### ISSUE TITLE
[Suggestion] Possibly re-add soul-sword?

### ISSUE THREAD

**Issue by FireController1847** [TheOnlySilverClaw/Reforged#180]
It seems to be a long request re-add that could benefit future versions of the mod (and would be great to see again!)

http://betterdungeons.wikia.com/wiki/The_Soul_Weapons_(removed)

**Comment by FireController1847** [comment]
I apologize, just realized this is the wrong mod 😨

**Comment by ThexXTURBOXx** [comment]
No problem ;)
