### ISSUE TITLE
Crafting arrow bundles doesn't work

### ISSUE THREAD

**Issue by mdfegan** [TheOnlySilverClaw/Reforged#182]
Hey, loving the mod so far, but I noticed that crafting bundles of arrows doesn't work. I tried putting the arrow next to the string as shown in the wiki, but nothing happens. I am able to get one with commands, but not by crafting.

**Comment by ThexXTURBOXx** [comment]
The Wiki is outdated. For anyone wondering, Arrow Bundles are crafted with **8** arrows and a string.
