### ISSUE TITLE
Reforged Integration appears to not function at all?

### ISSUE THREAD

**Issue by christopher0936** [TheOnlySilverClaw/Reforged#186]
Installed Reforged and Reforged Integration alongside Thaumcraft 6, only to find that there were no thaumium versions of any Reforged Weapons in JEI.

**Comment by ThexXTURBOXx** [comment]
Reforged Integration is only available for Minecraft 1.8.9, while Thaumcraft 6 is avilable for 1.10.2 and beyond. This can't work as you can see.
Thaumcraft 5 works fine though.
