### ISSUE TITLE
Disabling Battleaxes in the config doesn't disable Iron and Gold Battleaxes.

### ISSUE THREAD

**Issue by christopher0936** [TheOnlySilverClaw/Reforged#187]
Title. Need to disable them as they conflict in recipes with the TF hammers.

**Comment by ThexXTURBOXx** [comment]
Those can't be disbled, because they are needed for the Creative Tabs to work

**Comment by christopher0936** [comment]
Well can you add a config option to disable the creative tabs and sort the stuff into the vanilla tools and weapons tab?

**Comment by Sunconure11** [comment]
Why not use a custom item for the tab? A lot of mods seem to do it.
