### ISSUE TITLE
Goal seeking somehow conflicts with the appealing enchantment from aquaculture

### ISSUE THREAD

**Issue by Sunconure11** [TheOnlySilverClaw/Reforged#190]
Noticed this while working on my modpack, may want to look into it. Changing the ID does not help.

**Comment by Sunconure11** [comment]
![screenshot 2018-09-14 08 50 04](https://user-images.githubusercontent.com/5614902/45551254-478e9100-b7fb-11e8-95ea-627f77785544.png)

**Comment by ThexXTURBOXx** [comment]
Not reproducible (at least in the latest version)

![grafik](https://user-images.githubusercontent.com/12763829/188274567-f1a72468-fc9b-4736-9690-8aa77b816220.png)
