### ISSUE TITLE
Dart issue

### ISSUE THREAD

**Issue by Just-random-user** [TheOnlySilverClaw/Reforged#197]
Dart won't end, if you hold them in offhand and shoot a blowgun.

**Comment by xJon** [comment]
I think this is resolved in the latest release?

**Comment by xJon** [comment]
Actually this is still an issue with `0.7.6`

**Comment by xJon** [comment]
Actually this is still an issue with `0.7.6`, @ThexXTURBOXx would it be a quick fix?
