### ISSUE TITLE
Can I create a version of this mod which is more compatible with ic2?

### ISSUE THREAD

**Issue by gaogzs** [TheOnlySilverClaw/Reforged#200]
For example, increase the difficulty for muskets. The barrels are made from metal shafts, bullets are made of lead, shotgun bullets are made of iron powder.

**Comment by ThexXTURBOXx** [comment]
You may create a version for your private projects, but may not publish it.
If you want it to get published, you have to create a PR here and I will merge it and hopefully publish it at some point.

Edit: This would be better for the Reforged Integration mod, I guess. Look at my Github repositories and you can find the appropriate repo for that :)

**Comment by gaogzs** [comment]
> You may create a version for your private projects, but may not publish it.
> If you want it to get published, you have to create a PR here and I will merge it and hopefully publish it at some point.
> 
> Edit: This would be better for the Reforged Integration mod, I guess. Look at my Github repositories and you can find the appropriate repo for that :)

Thank you very much for that!

**Comment by gaogzs** [comment]
> You may create a version for your private projects, but may not publish it.
> If you want it to get published, you have to create a PR here and I will merge it and hopefully publish it at some point.
> 
> Edit: This would be better for the Reforged Integration mod, I guess. Look at my Github repositories and you can find the appropriate repo for that :)

Sorry to disturb you. I am pretty much a noob on Minecraft modding, I really want to merge my own idea into this project but all I can do is simply modifying the recipe file, I have no idea how to change the recipe only when another mod is loaded while disabling the original one.

**Comment by ThexXTURBOXx** [comment]
If you want to contribute, I can't really help you as I study at a university and need my time for that.
For modding tutorials, ask Google.
Also, there were many people the last weeks asking me, if they can take over development on this mod.
Did some famous guy promote it or something?

@ Everyone, who wants to contribute: **I won't help you in learning Java/Minecraft modding. If you want to contribute, learn it by _yourself_ as I did. If you aren't willing to do that, don't ask me if you may contribute. Only ask me, if you really want to do this _completely_ on your own and already know the basics of how modding works**
