### ISSUE TITLE
Permission to use repository?

### ISSUE THREAD

**Issue by tomatoBhutan** [TheOnlySilverClaw/Reforged#201]
On CurseForge, the custom license says to contact the owner of the repository if seeking permission to use code from it (paraphrasing). In the project description, also on CurseForge, there is a large red paragraph explaining that the project is currently halted and if anyone is interested in further developing the mod, to contact the owner on GitHub.

Here I am. I would like to use some parts of the repository to create an experience closer to the original Balkon’s Weapon Mod. May I? Thank you for your time.

**Comment by ThexXTURBOXx** [comment]
It depends on how much you will take from my mod. If you plan to take the entire mod and rewrite parts of it, you may only create a PR and I will maybe merge and publish it. If you only copy *parts* of it, and I don't mean e.g. textures by that, you may use them for your mod.
If you plan to rewrite the mod, go ahead and start from scratch, there is nothing and nobody, who can hold you back :)

What I mean by parts: The textures may not be taken. Also you may not copy entire classes and just change a few lines or something like that.
If you plan to copy the base structure of something, go ahead! Just don't copy too much. If you are unsure, ask again and I will look at it :)

**Comment by tomatoBhutan** [comment]
Sounds great! I don’t plan on copying _everything_.

**Comment by tomatoBhutan** [comment]
But if I may ask, what would you say is copying too much?

**Comment by ThexXTURBOXx** [comment]
Let me ask this: What exactly do you plan copying?
You may copy parts like the physics of the boomerang or something like that - just little parts, which may not be reproducible else.

**Comment by ThexXTURBOXx** [comment]
This repo is now under MIT License.
