### ISSUE TITLE
Puedo Crear un Paquete de texturas para mejorar gráficamente el mod ? 

### ISSUE THREAD

**Issue by Mcrevovler** [TheOnlySilverClaw/Reforged#202]
me gustaria saber si puedo hacer esto mejorandolo gráficamente, osea que tenga más pixeles para que así se vea mas decente

**Comment by ThexXTURBOXx** [comment]
Si quieres, puedes hacerlo. Sin embargo, todavía no lo publicaré en este mod. Si quieres, puedes poner tus texturas a disposición como un paquete de recursos.
