### ISSUE TITLE
Contribution Request

### ISSUE THREAD

**Issue by FireBlaim** [TheOnlySilverClaw/Reforged#204]
Hello the reforged team!

I want to contribute to your super mod by porting it to more recent versions (1.13, 1.16, etc...). I've been doing mods for about 5 years and I have experience.Also, I could improve the French translation of the mod because I'm French and also I saw some flaws in the translations.

Sincerely: Fire_Blaim

**Comment by ThexXTURBOXx** [comment]
Hello!
That sounds awesome! It would be best if you forked the project and make PRs at first and I can add you to the CurseForge and main GitHub repo later then :)

P.S.: As already said in some other issues here: The code is a **MESS** (I wasn't too experienced with how things work when I started working on the mod, so a cleanup could be needed at first lol :P)

**Comment by FireBlaim** [comment]
First of all thank you for your answer it's super nice of you so don't worry I will fork and clean your code!

Hurry to dev your mod !

**Comment by ThexXTURBOXx** [comment]
No problem! :)
Thank _you_, because many people will be very happy about these news then :D

**Comment by FireBlaim** [comment]
I'll contact you when I've finished the mod ;p

**Comment by FireBlaim** [comment]
I think I will completely change the code because many things have changed since MC 1.13.
