### ISSUE TITLE
Tekkit 2

### ISSUE THREAD

**Issue by ThexXTURBOXx** [TheOnlySilverClaw/Reforged#212]
Hi @xJon! For some reason, Gmail blocks my attempts to send you a preview version of the new build.
I have attached it here instead:
[Extract me to mods.zip](https://github.com/ThexXTURBOXx/Reforged/files/9482930/Extract.me.to.mods.zip)

Also, I cannot upload `jar` files to GitHub directly. So, you have to extract this `zip` file to your `mods/` folder manually :)

**Comment by xJon** [comment]
Hey @ThexXTURBOXx, awesome, thank you! So what do you mean by preview version?

**Comment by ThexXTURBOXx** [comment]
If everything works, that is the jar file that will be published to CF, Modrinth, and GitHub :)

**Comment by xJon** [comment]
I can't do completely thorough playtesting but it seems good!
If there are any future issues I'll be sure to report them, although the mod is probably quite stable at this point :)

**Comment by ThexXTURBOXx** [comment]
Thank you very much for the feeback!
I am just adding one more config option, but then I will publish it to GitHub, CF, and Modrinth.
I will let you know when you can download the official build.

**Comment by ThexXTURBOXx** [comment]
Published on GitHub, will publish to CF and Modrinth in the next few minutes
