### ISSUE TITLE
Guns cannot hit at point-blank range

### ISSUE THREAD

**Issue by AMPPL50** [TheOnlySilverClaw/Reforged#214]
One strange behavior I've found is that guns can't hit anything at a range less than about 3-4 blocks away from the player. I consider this to be an issue both because the original Balkon's mod didn't have this issue, and because it defeats one of the blunderbuss's biggest draws, which had always been it's high point-blank damage.

**Comment by ThexXTURBOXx** [comment]
Thanks for reporting this issue! It's reproducible and I hope I can fix it very soon.
I will let you know when I published a new version.

**Comment by ThexXTURBOXx** [comment]
I have bundled a new release. Could you test if the following fixes your issue?

[Extract Me.zip](https://github.com/ThexXTURBOXx/Reforged/files/10483627/Extract.Me.zip)

**Comment by AMPPL50** [comment]
Yes. The issue has been fixed.
PS. It does show the Blunderbuss pellets don't stack their damage (OG
Balkon's blunderbuss did because it didn't care about invincibility frames,
resulting in 40 damage per shot close-up) but that's honestly reasonably
workable.

**Comment by ThexXTURBOXx** [comment]
Thanks for the feedback. I will release the new version in a few minutes or hours. I also fixed the invincibility frames already. I just need to finish porting the changes to the other versions
